### ISSUE TITLE
[vitastor-mon] Mon's responsibilities

### ISSUE THREAD

**Issue by lnsyyj** [vitalif/vitastor#19]
Hi @vitalif ,

I have a question that I didn’t think about clearly. Why is a POST request sent in load_config?
Is the original intention of this code to read value from etcd? Or create a directory to etcd?

https://github.com/vitalif/vitastor/blob/712576ca75acf3a61812bafdf68518b3bf19f043/mon/mon.js#L1459

**Comment by vitalif** [comment]
Hi, why are you interested in the type of the request? :)
Do you want to say something like that it shouldn't make POST requests when it's not modifying anything?
If so then
1) Monitor DOES modify data in etcd on start - it acquires a lease, creates the /mon/master key and may do more things
2) It uses POST even for read requests because I don't care and it doesn't affect anything

**Comment by lnsyyj** [comment]
Oh, thanks, I see.
Does mon know that it is the master through etcd's /mon/master key association lease?

**Comment by vitalif** [comment]
Yes, exactly :-)
