### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by boniek83** [vitalif/vitastor#61]
What is the intention behind very atypical license? My understanding is that you want to keep all low level API libraries/proxy gateways that are specifically made to expose Vitastor to proper applications (whether commercially licenced or not) opensource. For example if I were to implement my own CSI driver for Kubernetes I would have to make it open source. Is that understanding correct?

**Comment by vitalif** [comment]
Hi! Yes, you're right about CSI. The idea is the same as the one behind GPL AGPL SSPL and so on, but applied to internal software which is invisible for users by design. In fact a lot of software is now implemented in this way, using various kinds of microservices instead of linking in one binary. And all this software easily kills the idea of copyleft. I think Mongo's SSPL is the previous attempt to do the same, but SSPL has really bad wording which just forbids cloud providers to use SSPL-licensed software. VNPL allows usage regardless of who you are (so it's not discriminatory) but tells that you should either build your cloud using only opensource technologies or purchase a commercial license. :-) so it's also a bit of groundwork for monetization. :-)
